### ISSUE TITLE
--test_output=streamed has broken

### ISSUE THREAD

**Issue by hanwen** [google/bazel#203] opened 2015-05-22 11:32 UTC
something is buffering up the output

$ bazel test --test_output=streamed //src/java_tools/singlejar:zipTests
Extracting Bazel installation...
Sending SIGTERM to previous Bazel server (pid=6524)... done.
.........
WARNING: Streamed test output requested so all tests will be run locally, without sharding, one at a time.
INFO: Found 1 test target...
[70 / 71] Testing //src/java_tools/singlejar:zipTests

[silence]

^C
Bazel caught interrupt signal; shutting down.
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
JUnit version 4.11
.............................................FAIL: //src/java_tools/singlejar:zipTests (see /home/hanwen/.cache/bazel/_bazel_hanwen/0c4198804daf70e6b39cbe31e3a971c4/bazel/bazel-out/local_linux-fastbuild/testlogs/src/java_tools/singlejar/zipTests/test.log).
Target //src/java_tools/singlejar:zipTests up-to-date:
  bazel-bin/src/java_tools/singlejar/zipTests.jar
  bazel-bin/src/java_tools/singlejar/zipTests
ERROR: build interrupted.
INFO: Elapsed time: 9.864s, Critical Path: 6.37s
//src/java_tools/singlejar:zipTests                                      FAILED

Executed 1 out of 1 tests: 1 fails locally.

**Comment by damienmg** [comment] 2015-05-26 08:06
I never seen a different behavior. If it's broken it has been for a long time. Assigning to hanwen to investigate.

**Comment by kayasoze** [comment] 2015-06-01 17:29
I can confirm that `--test_output=streamed` *works* for C++ unit tests (gtest).  Perhaps the issue is specific to Java, or to JUnit.

**Comment by hanwen** [comment] 2015-06-03 14:23
test_output=streamed looks for a magic header. Possibly, gUnit prints that automatically.

**Closed** 2015-06-05 10:45 UTC
