### ISSUE TITLE
strip error on Mac?

### ISSUE THREAD

**Issue by huahang** [google/bazel#290] opened 2015-07-09 05:45 UTC
When I was trying to build a binary target on Mac, I got the following error and it seems related to strip?

    $ bazel build thrift/compiler/cpp:*
    INFO: Found 47 targets...
    INFO: From Stripping thrift/compiler/cpp/thrift.stripped for //thrift/compiler/cpp:thrift:
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: unrecognized option: -p
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip [-AnuSXx] [-] [-d filename] [-s filename] [-R filename] [-o output] file [...] 
    ERROR: /Users/huahang/src/zerus/thrift/compiler/cpp/BUILD:66:1: Stripping thrift/compiler/cpp/thrift.stripped for //thrift/compiler/cpp:thrift failed: strip failed: error executing command /usr/bin/strip -S -p -o bazel-out/local_darwin-fastbuild/bin/thrift/compiler/cpp/thrift.stripped -R .gnu.switches.text.quote_paths -R .gnu.switches.text.bracket_paths -R .gnu.switches.text.system_paths ... (remaining 11 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    INFO: Elapsed time: 0.138s, Critical Path: 0.01s

**Comment by damienmg** [comment] 2015-07-12 20:55
This is a duplicate of issue #209.

When building :* target you also build .stripped target that use strip but it's incorrectly setted under OS X.

**Closed by damienmg** 2015-07-12 20:55 UTC
Labels: duplicate
