### ISSUE TITLE
hdrs_check doesn't work as intended

### ISSUE THREAD

**Issue by applmak** [google/bazel#179] opened 2015-05-06 13:14 UTC
LibTiff/BUILD file looks like:

```python
package(default_visibility=["//visibility:public"])

cc_library(
    name = "tiff",
    hdrs = glob(["**/*.h"]),
    srcs = glob(
        ["tif*.c"],
        exclude = ["tif_win32.c", "tif_unix.c", "tif_wince.c", "tif_vms.c"]
    ),
    includes = ["."],
    deps = [
        "//libs/freeimage/Source/LibJPEG:jpeg",
        "//libs/freeimage/Source/Zlib:zlib",
    ],
    hdrs_check = "loose",
)
```

Zlib/BUILD looks like:

```python
package(default_visibility=["//visibility:public"])

cc_library(
    name = "zlib",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.c"]),
    includes = ["."],
)
```

```
$ cd LibTiff && bazel build :tiff
ERROR: /Users/applmak/Desktop/chi-video-wall/libs/freeimage/Source/LibTIFF4/BUILD:3:1: undeclared inclusion(s) in rule '//libs/freeimage/Source/LibTIFF4:tiff':
this rule is missing dependency declarations for the following files included by 'libs/freeimage/Source/LibTIFF4/tif_zip.c':
  'libs/freeimage/Source/ZLib/zlib.h'.
Target //libs/freeimage/Source/LibTIFF4:tiff failed to build
```

Necessary bit of LibTiff/tif_zip.c:
```c++
...
#include "tif_predict.h"
#include "../ZLib/zlib.h"

#include <stdio.h>
...
```

Two problems: 
1) The hdrs_check isn't being disabled when I use 'loose'.
2) zlib.h is included in the glob of :zlib, but is still tripping the header checker, despite being added as a dep.

**Comment by janakdr** [comment] 2015-05-06 19:14
I'm unable to reproduce this issue with a toy example:
```
$ ls LibTiff
BUILD  tif_zip.c
$ cat LibTiff/BUILD
package(default_visibility=["//visibility:public"])

cc_library(
    name = "tiff",
    hdrs = glob(["**/*.h"]),
    srcs = glob(
        ["tif*.c"],
    ),
    includes = ["."],
    deps = [
        "//Zlib:zlib",
    ],
    hdrs_check = "loose",
)

$ cat LibTiff/tif_zip.c
#include "../Zlib/zlib.h"

$ ls Zlib
BUILD  zlib.c  zlib.h
$ cat Zlib/BUILD 
package(default_visibility=["//visibility:public"])

cc_library(
    name = "zlib",
    hdrs = glob(["*.h"]),
    srcs = glob(["*.c"]),
    includes = ["."],
)
$ cat Zlib/zlib.c  # empty file
$ cat Zlib/zlib.h # empty file
$ cd LibTiff
$ bazel build :tiff
Extracting Bazel installation...
......
INFO: Found 1 target...
Target //LibTiff:tiff up-to-date:
  bazel-bin/LibTiff/libtiff.a
  bazel-bin/LibTiff/libtiff.so
INFO: Elapsed time: 1.239s, Critical Path: 0.12s
```

Can you provide a complete repro?

**Comment by applmak** [comment] 2015-05-07 13:15
Hmm, I'm surprised by your simple repro. The only additional information I might be able to provide is that my WORKSPACE file is slightly farther away in  /Users/applmak/Desktop/chi-video-wall and, I'm using a Mac OS X computer. I'll see if I can find a minimum zip that demonstrates the problem.

**Comment by ulfjack** [comment] 2015-07-23 12:17
Closing due to old age and non-reproducibility.

**Closed by ulfjack** 2015-07-23 12:17 UTC
Labels: P3
