### ISSUE TITLE
Allow setting paths to android NDK and SDK from bazelrc

### ISSUE THREAD

**Issue by mrdomino** [google/bazel#326] opened 2015-07-24 01:09 UTC
It'd be great to be able to set the paths to the android SDK and NDK tools without having to edit the WORKSPACE file, to accommodate variations among dev environments. I guess build:android --android_sdk_path=... would make sense, for instance?

**Comment by damienmg** [comment] 2015-07-27 08:57
Lukacs to expose his plan on this one.

**Comment by lberki** [comment] 2015-07-27 09:53
My plan for this one was that you'd have references in your WORKSPACE file to different SDKs, i.e.

```
android_sdk_repository(name="lollipop", ...)
android_sdk_repository(name="kitkat", ...)
```

And then you'd be able to select between them using the `--android_sdk_top` command line option. You can actually do this with Bazel right now (modulo any bugs)

What variations in dev environments you want to accommodate? Variations for a single developer (i.e. sometimes I want to build for L, sometimes for M) or variations between different developers (i.e. Alice has her SDK installed at a different place than Bob)?

**Comment by mrdomino** [comment] 2015-07-27 13:41
Variations between developers: I have my sdk at /Users/me/sdk, someone else
has it at /opt/local/android-sdk-macosx, someone else has it at
/home/them/sdk.

I suppose this is achievable today with an ignored symlink and instructions
to set it appropriately. Then the WORKSPACE points to the symlink and no
one has to worry about keeping local commits out of the repo.

**Comment by lberki** [comment] 2015-07-27 13:42
My master plan for that was user-specific WORKSPACE files. Once "load()" works in WORKSPACE files (they probably do today), you can do a load("WORKSPACE.user") in the WORKSPACE file and add WORKSPACE.user to your .gitignore.

Would this work?

**Comment by mrdomino** [comment] 2015-07-27 15:22
Yup, that'd be awesome.

**Comment by lberki** [comment] 2015-07-28 11:29
Filed https://github.com/google/bazel/issues/337 .

Then I close this as Working as Intended, since it doesn't really mesh with our medium term plans.

**Comment by lberki** [comment] 2015-07-28 11:29
Filed https://github.com/google/bazel/issues/337 .

Then I close this as Working as Intended, since it doesn't really mesh with
our medium term plans.

On Mon, Jul 27, 2015 at 5:22 PM, Steven Dee <notifications@github.com>
wrote:

> Yup, that'd be awesome.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/326#issuecomment-125243274>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Dienerstrasse 12 | 80331 München | Germany |
Geschäftsführer:
Graham Law, Christine Elizabeth Flores | Registergericht und -nummer:
Hamburg, HRB 86891

**Closed by lberki** 2015-07-28 11:29 UTC
Labels: enhancement, P3
