### ISSUE TITLE
Native rules should expose Skylark providers

### ISSUE THREAD

**Issue by schroederc** [google/bazel#193] opened 2015-05-15 23:05 UTC
Rules like cc_library/java_library should expose Skylark providers.  Then Skylark rules can interoperate, and for instance, link against C++ libraries and compile with their headers.

**Comment by davidzchen** [comment] 2015-05-16 04:33
+1 this would be awesome to have.

Also discussed in the following thread: https://groups.google.com/forum/#!topic/bazel-discuss/vluCSjYArTA

**Comment by damienmg** [comment] 2015-05-18 06:21
Technically this is a duplicate of #146

**Closed** 2015-05-18 12:24 UTC
Labels: enhancement, P2
