### ISSUE TITLE
Workspace status files don't contain much useful data

### ISSUE THREAD

**Issue by lberki** [google/bazel#210] opened 2015-05-26 12:35 UTC
stable-status.txt and volatile-status.txt only contain --embed_label.

It would be nice if they actually contained something useful (hostname, username, current time...)

**Comment by damienmg** [comment] 2015-05-26 12:37
Assignig to Lukacs for tracking the bug. Reassign at will :)

**Comment by damienmg** [comment] 2015-06-19 12:01
It is actually somehow a duplicate of #216. At least the fix Ming sent is addressing this issue.

**Closed by damienmg** 2015-06-19 12:01 UTC
Labels: P2
