### ISSUE TITLE
cc_library hdrs without an extension

### ISSUE THREAD

**Issue by ethanrublee** [google/bazel#182] opened 2015-05-06 16:58 UTC
using bazel sha: ed7c0f35768aab226299d7ef5d253e760a89ed91

I'm attempting to create a cc_library for Eigen, which has headers with no extension, e.g. Eigen/Core

So, declaring a cc_library target like:

```python

eigen_header_files = glob(
    ["Eigen/**"],
    exclude = ["Eigen/**/CMakeLists.txt"],
)

cc_library(
    name = "eigen3",
    includes = ["."],
    hdrs=eigen_header_files,
)
```

Results in an error like:
```
third_party/eigen3/BUILD:15:10: in hdrs attribute of cc_library rule //third_party/eigen3:eigen3: '//third_party/eigen3:Eigen/UmfPackSupport' does not produce any cc_library hdrs files (expected .h, .hh, .hpp, .hxx or .inc).
ERROR: Analysis of target '//third_party/eigen3:eigen3' failed; build aborted.
```

I hacked the hdrs check, to allow any file:
```patch
diff --git a/src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppRuleClasses.java b/src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppRuleClasses.java
index 1b08af7..63e72d9 100644
--- a/src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppRuleClasses.java
+++ b/src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppRuleClasses.java
@@ -741,7 +741,7 @@ public class BazelCppRuleClasses {
           </p>
           <!-- #END_BLAZE_RULE.ATTRIBUTE -->*/
           .add(attr("hdrs", LABEL_LIST).orderIndependent().direct_compile_time_input()
-              .allowedFileTypes(CPP_HEADER))
+               .allowedFileTypes(FileTypeSet.ANY_FILE))
           // TODO(bazel-team): document or remove.
           .add(attr("linkstamp", LABEL).allowedFileTypes(CPP_SOURCE, C_SOURCE))
           .build();
```

But not sure how this case should be handled.  Perhaps a blacklist would be better, because there are other common extensions, such as "ipp" in boost.

Another note, this is not blocking at the moment, because the eigen3 library is perfectly usable without specifying the hdrs field...  But I assume that will break in the future.

**Comment by lberki** [comment] 2015-05-07 13:17
Closing this as a duplicate of 

https://github.com/google/bazel/issues/164

. Will submit a patch real soon now.

**Closed by lberki** 2015-05-07 13:17 UTC
