### ISSUE TITLE
bazel build somecpp_library fails if it depends on another library

### ISSUE THREAD

**Issue by pmbethe09** [google/bazel#67] opened 2015-03-26 21:38 UTC
make the following:
cc_library(name="A", ...)
cc_library(name="B", srcs=["b.cpp"], deps=[":A"], ...)
cc_binary(name="main", ..., deps=[":B"])

bazel build :main works just fine (it correctly puts libA.so and libB.so on the link line)
bazel build :A - same
but bazel build :B will fail with:

From Linking lib/libB.so:
Undefined symbols for architecture x86_64:
  "...."
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: lib/BUILD:3:1: Linking of rule '//lib:lib' failed: gcc failed: error executing command /usr/bin/gcc -shared -o bazel-out/local_darwin-fastbuild/bin/lib/libB.so bazel-out/local_darwin-fastbuild/bin/lib/_objs/lib/lib/b.pic.o -lstdc++ -B/usr/bin -Wl,-S: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

It appears that liba.so is missing from the command

**Comment by lberki** [comment] 2015-03-27 10:45
This is very surprising. Couldn't reproduce with this BUILD file on Linux, though:

cc_library(
    name = "a",
    srcs = ["a.cpp"],
)

cc_library(
    name = "b",
    srcs = ["b.cpp"],
    deps = [":a"],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [":b"],
)

Assigning to Damien since he knows a tad more about Mac than I do.

**Comment by damienmg** [comment] 2015-03-27 11:32
Cannot reproduce:

# Regression test for https://github.com/google/bazel/issues/67
# C++ library depedending on C++ library fails to compile on Darwin
function test_cpp_libdeps() {
    mkdir -p pkg
    cat <<'EOF' >pkg/BUILD
cc_library(
  name = "a",
  srcs = ["a.cc"],
)

cc_library(
  name = "b",
  srcs = ["b.cc"],
  deps = [":a"],
)

cc_binary(
  name = "main",
  srcs = ["main.cc"],
  deps = [":b"],
)
EOF

    cat <<'EOF' >pkg/a.cc
#include <string>

std::string get_hello(std::string world) {
  return "Hello, " + world + "!";
}
EOF

    cat <<'EOF' >pkg/b.cc
#include <string>
#include <iostream>

std::string get_hello(std::string);

void print_hello(std::string world) {
  std::cout << get_hello(world) << std::endl;
}
EOF

    cat <<'EOF' >pkg/main.cc
#include <string>
void print_hello(std::string);

int main() {
   print_hello(std::string("World"));
}
EOF

    bazel run //pkg:main >& $TEST_log \
	|| fail "Failed to run //pkg:main"
    expect_log "Hello, World!";
}

Succeed on my mac I will commit it to share it but the output is clean

**Comment by damienmg** [comment] 2015-03-27 11:46
\o/ I have a failing test

**Comment by pmbethe09** [comment] 2015-03-27 13:09
Add an a.h which b.cc includes and calls a function from.

**Comment by damienmg** [comment] 2015-03-27 17:48
The problem is that darwin clang expect to have all the dependency provided at compile time. It is not going to be fast to fix.

**Comment by damienmg** [comment] 2015-03-29 20:37
I edited the test case in my previous message to have an actually failing one for future reference.

**Comment by kayasoze** [comment] 2015-04-23 22:47
I've encountered this issue as well.

**Comment by aimeeble** [comment] 2015-04-30 00:48
I've been hitting this too. I've worked around the issue by adding:

    linker_flag: "-undefined"
    linker_flag: "dynamic_lookup"

into my CROSSTOOL file. Not sure the larger implications of this style lookup though. But, it's enough for me to actually compile, so I'm happy for now.

**Closed** 2015-05-18 09:36 UTC
