### ISSUE TITLE
Bazel fails to build all targets in my project, protobuf "crosses boundary of subpackages"

### ISSUE THREAD

**Issue by kwatts** [google/bazel#103] opened 2015-04-07 21:37 UTC
I just updated my version of bazel, and I can no longer build all packages from the root. 

Bazel version: c2dd80f773174e496dd53c40d287a7e7b705b960

It looks like the rules in //third_party/protobuf are crossing subpackages:
http://bazel.io/docs/build-ref.html

```
$ bazel build ...
ERROR: /home/kw/bazel/output/classes/BUILD:86:1: //output/classes:srcs: invalid label 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class' in element 72 of attribute 'srcs' in 'filegroup' rule: invalid target name 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class': target names may not contain '$'.
ERROR: /home/kw/bazel/third_party/BUILD:12:12: Label '//third_party:protobuf/protoc.amd64' crosses boundary of subpackage 'third_party/protobuf' (have you deleted third_party/protobuf/BUILD? If so, use the --deleted_packages=third_party/protobuf option).
ERROR: /home/kw/bazel/third_party/BUILD:12:12: Label '//third_party:protobuf/protoc.darwin' crosses boundary of subpackage 'third_party/protobuf' (have you deleted third_party/protobuf/BUILD? If so, use the --deleted_packages=third_party/protobuf option).
ERROR: /home/kw/bazel/third_party/BUILD:103:12: Label '//third_party:protobuf/protobuf-2.5.0.jar' crosses boundary of subpackage 'third_party/protobuf' (have you deleted third_party/protobuf/BUILD? If so, use the --deleted_packages=third_party/protobuf option).
ERROR: /home/kw/bazel/third_party/BUILD:12:12: Label '//third_party:protobuf/protoc.exe' crosses boundary of subpackage 'third_party/protobuf' (have you deleted third_party/protobuf/BUILD? If so, use the --deleted_packages=third_party/protobuf option).
ERROR: error loading package 'output/classes': Package 'output/classes' contains errors.
INFO: Elapsed time: 0.130s
```

**Comment by fare** [comment] 2015-04-07 22:57
Ouch. These are classes provided by the auto_value jar from maven. Apparently, that doesn't make bazel happy. I'll be working on it.

**Comment by fare** [comment] 2015-04-07 23:02
and where is that package third_party/protobuf coming from? There's no BUILD file in there. Or is it confusing multiple workspaces?

**Comment by kchodorow** [comment] 2015-04-07 23:05
If I run it on a clean repo, I get:

```
$ output/bazel build ...
ERROR: /Users/kchodorow/gitroot/bazel/output/classes/BUILD:86:1: //output/classes:srcs: invalid label 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class' in element 72 of attribute 'srcs' in 'filegroup' rule: invalid target name 'autovalue/shaded/com/google/common/auto/common/MoreElements$1.class': target names may not contain '$'.
ERROR: package contains errors: output/classes.
ERROR: error loading package 'output/classes': Package 'output/classes' contains errors.
INFO: Elapsed time: 1.811s
```

**Comment by fare** [comment] 2015-04-07 23:06
What is output/classes ? It doesn't smell like source code, but output files being confused for source code.

**Comment by kchodorow** [comment] 2015-04-07 23:09
Yeah, I'm not sure if this is actually an autovalue problem, Fare.  I don't think output/ should have any BUILD files in it.  It's generated by compile.sh.

**Comment by fare** [comment] 2015-04-07 23:13
More generally, we should exclude any output directories from scanning of source code for the purpose of ...

**Comment by fare** [comment] 2015-04-07 23:14
We didn't discover that earlier because the setup at Google avoids putting the outputs under the top workspace directory.

**Comment by damienmg** [comment] 2015-04-08 09:03
You should not build the world :) Try bazel build //src/...

We are not building the world in our automated build. And I don't think we should support it. (//tools will never be able to compile everything for instance).

**Comment by damienmg** [comment] 2015-04-08 09:04
nb: output is an artifact of compile.sh and we cannot add special case for that in bazel. I am closing this issue.

**Comment by ethanrublee** [comment] 2015-04-09 04:07
So I think I found part of the problem...

Lets say we have two bazel workspaces:

Upon building a recent version of bazel ( mine's checked out at 41c2f9ee09751a0709c02e2e8dfdca227ccc45b0), it generates ``.bazelrc``

```
$ cd bazel/
$ ./compile.sh 
Compiling Java stubs for protocol buffers...
$ cat ~/.bazelrc 
build --package_path %workspace%:/home/rublee/bazel
```

my_workspace can be reproduced with:
```sh
mkdir ~/my_workspace
cp -R ~/bazel/base_workspace/third_party  ~/bazel/base_workspace/tools ~/my_workspace
mkdir ~/my_workspace/examples
cp -r ~/bazel/base_workspace/examples/cpp ~/my_workspace/examples/
echo 'workspace(name = "my_workspace")' > ~/my_workspace/WORKSPACE
```

With the generated ~/.bazelrc I get the same error described above:
```
$ cat ~/.bazelrc
build --package_path %workspace%:/home/rublee/bazel
$ cd ~/my_workspace
$ ~/bazel/output/bazel build ...
...
ERROR: error loading package 'output/classes': Package 'output/classes' contains errors.
INFO: Elapsed time: 0.382s
```
Now if I change the ``~/.bazelrc``, by removing the entry for ``/home/rublee/bazel`` it works.
```
$ cat ~/.bazelrc
build --package_path %workspace%
$ cd ~/my_workspace
$ ~/bazel/output/bazel build ...
INFO: Found 5 targets...
INFO: Elapsed time: 1.522s, Critical Path: 0.02s
```

Is this behavior really intentional?  It seems very reasonable to build all of my_workspace.

**Comment by damienmg** [comment] 2015-04-09 08:01
No it is a side-effect of bazel bootstrapping and we are actually working on a better approach to providing tools outside of bazel.

You can put /home/rublee/bazel/base_workspace instead of /home/rublee/bazel in your bazelrc and that should remove it.

**Comment by claridge** [comment] 2015-04-09 16:14
I'm joining the discusion from #107, and I just figured out the root of my own confusion. Why does compile.sh now create a .bazelrc in my home directory, or tell me to add the Bazel repo root to my home directory if I already have one?

I have a separate project that I'm building with Bazel, and I rebuild Bazel itself fairly often to catch updates. Having its compilation touch global state like that is...surprising.

**Comment by kchodorow** [comment] 2015-04-09 16:23
It's so you don't need a symlink to tools/ into your project directory (see bazel.io/blog/2015/04/06/Simplified-Workspace-Creation.html).  compile.sh won't modify it after creating it, so feel free to make it an empty file if you prefer the tools/ symlink.  Note that every time you compile your tools will still be updated globally, though.

**Comment by claridge** [comment] 2015-04-09 16:59
Ah, neat! I'll have to start watching the blog.

Following damienmg's suggestion above, could you make compile.sh use <Bazel root>/base_workspace instead? Then other projects can still "build ...".

**Comment by kchodorow** [comment] 2015-04-09 17:22
Good idea, that way it can contain exactly the directories we want and nothing extra.  I actually removed base_workspace in that commit, let me just add it back... (and you'll have to modify .bazelrc when you recompile).

**Comment by claridge** [comment] 2015-04-10 21:23
I just reinstalled with the update. Thanks!

**Closed** 2015-04-13 18:19 UTC
