### ISSUE TITLE
closure_js_binary is unable to find goog.async.Deferred

### ISSUE THREAD

**Issue by AmandaCameron** [google/bazel#275] opened 2015-07-02 16:48 UTC
I'm not sure what's up with this, but goog.async.Deferred isn't getting found from the closure library at all for me.

`bazel 'query deps(@closure_library/closure_library)'` shows the deferred.js being listed, however I'm still getting compiler errors when I try and `goog.require('goog.async.Deferred')`.

I'm fairly certine it's not a ARG_MAX problem.

I'm on OS X Yosemite.

If you need any further information,  just ask. :)

**Comment by damienmg** [comment] 2015-07-02 16:50
+Kamil Jiwa <kjiwa@google.com>

**Comment by kjiwa** [comment] 2015-07-02 17:34
I can repro this.

When I query that target, I see all of the JS listed under ```$CLOSURE_LIBRARY_ROOT/closure/goog```, but goog.async.Deferred is actually defined in ```$CLOSURE_LIBRARY_ROOT/third_party/closure/goog/mochikit/async/deferred.js```.

The rules should be including the third_party files in the build. In the closure_library JS rule I define srcs to include that directory.

```python
closure_js_library(
    name = "closure_library",
    srcs = glob(
        [   
            "closure/goog/**/*.js",
            "third_party/closure/goog/**/*.js",
        ],
        exclude = [
            "closure/goog/**/*_test.js",
            "closure/goog/demos/**/*.js",
        ],
    ),
    visibility = ["//visibility:public"],
)
```

When I examine the command line being sent to JsCompiler I notice that no third_party files are listed either. This indicates to me that ctx.files.srcs isn't populated with those files either.

Did I misuse glob() or somehow define srcs incorrectly?

**Comment by damienmg** [comment] 2015-07-02 17:53
It looks ok from my side. I can test and have a look tomorrow morning.

**Comment by kjiwa** [comment] 2015-07-02 17:54
This is the output on my side from ```bazel query "deps(@closure_library//:closure_library)"```: http://pastebin.com/yLv35cTx.

**Comment by AmandaCameron** [comment] 2015-07-02 17:59
This is the output on my side, for reference. a quick grep *does* show the deferred.js in there, however I'm not sure how to check if it's getting sent to the JsCompile action.

https://gist.github.com/c602db4ec2f77fee13c8

**Comment by kjiwa** [comment] 2015-07-02 18:02
You can check if it's being sent to JsCompiler if you run your build with ```--verbose_failures```. When it fails, the command line should be part of the output.

**Comment by AmandaCameron** [comment] 2015-07-02 18:05
It's not showing up in bazel build :target --verbose_failures 2>&1 | grep deferred.js

**Comment by damienmg** [comment] 2015-07-03 10:11
Adding Lukacs to the discussion

**Comment by lberki** [comment] 2015-07-03 14:57
Ugh, I didn't have much time for this and I couldn't reproduce it in what
little time I had today.

On Fri, Jul 3, 2015 at 12:11 PM, Damien Martin-Guillerez <
notifications@github.com> wrote:

> Adding Lukacs to the discussion
>
> On Thu, Jul 2, 2015 at 8:06 PM Amanda Cameron <notifications@github.com>
> wrote:
>
> > It's not showing up in bazel build :target --verbose_failures 2>&1 | grep
> > deferred.js
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/bazel/issues/275#issuecomment-118112408>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/275#issuecomment-118305249>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Dienerstrasse 12 | 80331 München | Germany |
Geschäftsführer:
Graham Law, Christine Elizabeth Flores | Registergericht und -nummer:
Hamburg, HRB 86891

**Comment by kjiwa** [comment] 2015-07-03 19:06
I tested this on Fedora 21 and Ubuntu 14.04.2. The behaviour is the same on each platform. I tried setting ```srcs``` to _only_ reference the code in ```$CLOSURE_LIBRARY_ROOT/third_party``` and found that it was still being filtered out (```srcs = glob(["third_party/closure/goog/**/*.js"])```).

On a hunch I renamed the ```third_party``` directory to ```3p``` and updated the ```closure_library``` build target. After the change I started to see the files listed in my ```bazel query```. I was also able to compile JS code relying on ```goog.async.Deferred```. @AmandaCameron does a rename make your build work?

* ```bazel query``` with ```third_party```: https://gist.github.com/kjiwa/214d8a6ced4472f54513
* ```bazel query``` with ```3p```: https://gist.github.com/kjiwa/157f34014a815ca695a3

**Comment by AmandaCameron** [comment] 2015-07-03 19:12
With a couple of additions to the excludes = glob bit (to excluse 3p's tests and demos) yes. It makes the namespace available to my code.

**Comment by kjiwa** [comment] 2015-07-03 19:22
Thanks. I'll make an update to the BUILD file to exclude the third_party tests. I think this is a bug in Bazel that is preventing files in directories named "third_party" from being referenced.

A simple repro:

1. Create a dummy repository (e.g. ```src/my_repo```)
2. Add the repository to your Bazel workspace
3. ```bazel query```

When creating the repository, also create a directory structure beneath it with some files:

```bash
mkdir -p src/my_repo/{src,third_party}
touch src/my_repo/src/{t,u,v}.txt
touch src/my_repo/third_party/{a,b,c}.txt
```

In your Bazel workspace, add this to your WORKSPACE:

```python
new_local_repository(
    name = "repo_with_third_party_dir",
    build_file = "tools/build_rules/repo_with_third_party_dir.BUILD",
    path = "/home/kjiwa/src/my_repo",
)
```

Finally, add ```tools/build_rules/repo_with_third_party_dir.BUILD``` to your workspace:

```python
filegroup(  
    name = "repo_with_third_party_dir",
    srcs = glob(["**/*.txt"]),
)
```

Running ```bazel query "deps(@repo_with_third_party_dir//:repo_with_third_party_dir)" yields the following:

```bash
$ bazel query "deps(@repo_with_third_party_dir//:repo_with_third_party_dir)" 
@repo_with_third_party_dir//:repo_with_third_party_dir
@repo_with_third_party_dir//:src/v.txt
@repo_with_third_party_dir//:src/u.txt
@repo_with_third_party_dir//:src/t.txt
```

Note that the files in ```third_party``` are not listed.

```bash
$ find $HOME/src/my_repo -type f 
/home/kjiwa/src/my_repo/third_party/a.txt
/home/kjiwa/src/my_repo/third_party/b.txt
/home/kjiwa/src/my_repo/third_party/c.txt
/home/kjiwa/src/my_repo/src/t.txt
/home/kjiwa/src/my_repo/src/u.txt
/home/kjiwa/src/my_repo/src/v.txt
```

**Comment by lberki** [comment] 2015-07-06 10:59
Now that I put my brain into gear, it's clear what's wrong (the issue was
that glob was looking for BUILD files in the main repository even though
the glob was run in the new_local_repository). I have a change out to fix
it. It's not a theoretically pure fix, though, so I may have to do some
convincing in the code review.

On Fri, Jul 3, 2015 at 9:22 PM, Kamil Jiwa <notifications@github.com> wrote:

> Thanks. I'll make an update to the BUILD file to exclude the third_party
> tests. I think this is a bug in Bazel that is preventing files in
> directories named "third_party" from being referenced.
>
> A simple repro:
>
>    1. Create a dummy repository (e.g. src/my_repo)
>    2. Add the repository to your Bazel workspace
>    3. bazel query
>
> When creating the repository, also create a directory structure beneath it
> with some files:
>
> mkdir -p src/my_repo/{src,third_party}
> touch src/my_repo/src/{t,u,v}.txt
> touch src/my_repo/third_party/{a,b,c}.txt
>
> In your Bazel workspace, add this to your WORKSPACE:
>
> new_local_repository(
>     name = "repo_with_third_party_dir",
>     build_file = "tools/build_rules/repo_with_third_party_dir.BUILD",
>     path = "/home/kjiwa/src/my_repo",
> )
>
> Finally, add tools/build_rules/repo_with_third_party_dir.BUILD to your
> workspace:
>
> filegroup(
>     name = "repo_with_third_party_dir",
>     srcs = glob(["**/*.txt"]),
> )
>
> Running ```bazel query
> "deps(@repo_with_third_party_dir//:repo_with_third_party_dir)" yields the
> following:
>
> $ bazel query "deps(@repo_with_third_party_dir//:repo_with_third_party_dir)"
> @repo_with_third_party_dir//:repo_with_third_party_dir
> @repo_with_third_party_dir//:src/v.txt
> @repo_with_third_party_dir//:src/u.txt
> @repo_with_third_party_dir//:src/t.txt
>
> Note that the files in third_party are not listed.
>
> $ find $HOME/src/my_repo -type f
> /home/kjiwa/src/my_repo/third_party/a.txt
> /home/kjiwa/src/my_repo/third_party/b.txt
> /home/kjiwa/src/my_repo/third_party/c.txt
> /home/kjiwa/src/my_repo/src/t.txt
> /home/kjiwa/src/my_repo/src/u.txt
> /home/kjiwa/src/my_repo/src/v.txt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/bazel/issues/275#issuecomment-118410855>.
>



-- 
Lukács T. Berki | Software Engineer | lberki@google.com |

Google Germany GmbH | Dienerstrasse 12 | 80331 München | Germany |
Geschäftsführer:
Graham Law, Christine Elizabeth Flores | Registergericht und -nummer:
Hamburg, HRB 86891

**Comment by kjiwa** [comment] 2015-07-08 20:12
Thanks. I can confirm that https://github.com/google/bazel/commit/33aa1e1afd9f0c35f8ccadcf8bf8f29357ca2878 fixes the issue.

I've also submitted a CL to add ```third_party/closure/goog/**/*_test.js``` to the list of exclusions. It should get committed in the next day or two, pending approval.

**Comment by kjiwa** [comment] 2015-07-10 19:12
Resolved in https://github.com/google/bazel/commit/c7d2c54d7a78d4515d4788e31c5474b8089ec37c.

**Closed** 2015-07-12 06:18 UTC
