### ISSUE TITLE
executed/total count is nonsensical for tests

### ISSUE THREAD

**Issue by janakdr** [google/bazel#298] opened 2015-07-12 11:07 UTC
Running mostly cached tests, I get
INFO: Elapsed time: 73.106s, Critical Path: 72.65s
//src/test/shell/bazel:bazel_example_test                   (3/0 cached) PASSED
//src/java_tools/buildjar:BazelJavaCompilerTest             (1/0 cached) PASSED
//src/java_tools/singlejar:tests                            (1/0 cached) PASSED
//src/test/java:actions_test                                (1/0 cached) PASSED
//src/test/java:analysis_actions_test                       (1/0 cached) PASSED
//src/test/java:analysis_config_test                        (1/0 cached) PASSED
//src/test/java:analysis_constraints_test                   (1/0 cached) PASSED
//src/test/java:analysis_select_test                        (1/0 cached) PASSED
//src/test/java:analysis_test                               (1/0 cached) PASSED
//src/test/java:common-rules-tests                          (1/0 cached) PASSED
//src/test/java:foundations_test                            (1/0 cached) PASSED
//src/test/java:options_test                                (1/0 cached) PASSED
//src/test/java:packages_test                               (1/0 cached) PASSED
//src/test/java:shell_test                                  (1/0 cached) PASSED
//src/test/java:skyframe_test                               (1/0 cached) PASSED
//src/test/java:syntax_test                                 (1/0 cached) PASSED
//src/test/java:windows_test                                (1/0 cached) PASSED
//src/test/java:ziputils-tests                              (1/0 cached) PASSED
//src/test/shell:bashunit_test                              (1/0 cached) PASSED
//src/test/shell/bazel:bazel_docgen_test                    (1/0 cached) PASSED
//src/test/shell/bazel:bazel_execute_testlog                (1/0 cached) PASSED
//src/test/shell/bazel:bazel_rules_test                     (1/0 cached) PASSED
//src/test/shell/bazel:bazel_rust_example_test              (1/0 cached) PASSED
//src/test/shell/bazel:bazel_test_test                      (1/0 cached) PASSED
//src/test/shell/bazel:bazel_worker_test                    (1/0 cached) PASSED
//src/test/shell/bazel:bazel_workspace_status_test          (1/0 cached) PASSED
//src/test/shell/bazel:empty_package_test                   (1/0 cached) PASSED
//src/test/shell/bazel:external_integration_test            (1/0 cached) PASSED
//src/test/shell/bazel:local_repository_test                (1/0 cached) PASSED
//src/test/shell/bazel:location_test                        (1/0 cached) PASSED
//src/test/shell/bazel:runfiles_test                        (1/0 cached) PASSED
//src/test/shell/bazel:workspace_test                       (1/0 cached) PASSED

**Comment by damienmg** [comment] 2015-07-12 21:06
Duplicate of issue #218

**Closed by damienmg** 2015-07-12 21:06 UTC
